# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# Just to Commit

@chef_1 = Chef.create!(name: "chef 1")
@chef_2 = Chef.create!(name: "chef 2")
@chef_3 = Chef.create!(name: "chef 3")

@dish_1 = @chef_1.dishes.create!(name: "dish 1", description: "1 dish", calories: 100)
@dish_2 = @chef_1.dishes.create!(name: "dish 2", description: "2 dish", calories: 200)
@dish_3 = @chef_1.dishes.create!(name: "dish 3", description: "3 dish", calories: 300)
@dish_4 = @chef_2.dishes.create!(name: "dish 4", description: "4 dish", calories: 400)
@dish_5 = @chef_2.dishes.create!(name: "dish 5", description: "5 dish", calories: 500)
@dish_6 = @chef_2.dishes.create!(name: "dish 6", description: "6 dish", calories: 600)
@dish_7 = @chef_2.dishes.create!(name: "dish 7", description: "7 dish", calories: 700)
@dish_8 = @chef_3.dishes.create!(name: "dish 7", description: "8 dish", calories: 800)
@dish_9 = @chef_3.dishes.create!(name: "dish 8", description: "9 dish", calories: 900)
@dish_10 = @chef_3.dishes.create!(name: "dish 9", description: "10 dish", calories: 1000)
@dish_11 = @chef_3.dishes.create!(name: "dish 10", description: "11 dish", calories: 1100)
@dish_12 = @chef_3.dishes.create!(name: "dish 10", description: "12 dish", calories: 1200)

@ingredient_1 = Ingredient.create!(name: "ingredient 1")
@ingredient_2 = Ingredient.create!(name: "ingredient 2")
@ingredient_3 = Ingredient.create!(name: "ingredient 3")
@ingredient_4 = Ingredient.create!(name: "ingredient 4")
@ingredient_5 = Ingredient.create!(name: "ingredient 5")
@ingredient_6 = Ingredient.create!(name: "ingredient 6")

@dish_ingredient_1 = @dish_1.dish_ingredients.create!(ingredient_id: @ingredient_1.id)
@dish_ingredient_2 = @dish_1.dish_ingredients.create!(ingredient_id: @ingredient_2.id)
@dish_ingredient_3 = @dish_2.dish_ingredients.create!(ingredient_id: @ingredient_1.id)
@dish_ingredient_4 = @dish_2.dish_ingredients.create!(ingredient_id: @ingredient_3.id)
@dish_ingredient_5 = @dish_3.dish_ingredients.create!(ingredient_id: @ingredient_1.id)
@dish_ingredient_6 = @dish_3.dish_ingredients.create!(ingredient_id: @ingredient_4.id)
@dish_ingredient_7 = @dish_4.dish_ingredients.create!(ingredient_id: @ingredient_1.id)
@dish_ingredient_8 = @dish_4.dish_ingredients.create!(ingredient_id: @ingredient_5.id)
@dish_ingredient_9 = @dish_5.dish_ingredients.create!(ingredient_id: @ingredient_1.id)
@dish_ingredient_10 = @dish_5.dish_ingredients.create!(ingredient_id: @ingredient_6.id)
@dish_ingredient_11 = @dish_6.dish_ingredients.create!(ingredient_id: @ingredient_2.id)
@dish_ingredient_12 = @dish_6.dish_ingredients.create!(ingredient_id: @ingredient_3.id)
@dish_ingredient_13 = @dish_7.dish_ingredients.create!(ingredient_id: @ingredient_2.id)
@dish_ingredient_14 = @dish_7.dish_ingredients.create!(ingredient_id: @ingredient_4.id)
@dish_ingredient_15 = @dish_8.dish_ingredients.create!(ingredient_id: @ingredient_2.id)
@dish_ingredient_16 = @dish_8.dish_ingredients.create!(ingredient_id: @ingredient_5.id)
@dish_ingredient_17 = @dish_9.dish_ingredients.create!(ingredient_id: @ingredient_2.id)
@dish_ingredient_18 = @dish_9.dish_ingredients.create!(ingredient_id: @ingredient_6.id)
@dish_ingredient_19 = @dish_10.dish_ingredients.create!(ingredient_id: @ingredient_3.id)
@dish_ingredient_20 = @dish_10.dish_ingredients.create!(ingredient_id: @ingredient_4.id)
@dish_ingredient_21 = @dish_11.dish_ingredients.create!(ingredient_id: @ingredient_3.id)
@dish_ingredient_22 = @dish_11.dish_ingredients.create!(ingredient_id: @ingredient_5.id)
@dish_ingredient_23 = @dish_12.dish_ingredients.create!(ingredient_id: @ingredient_3.id)
@dish_ingredient_24 = @dish_12.dish_ingredients.create!(ingredient_id: @ingredient_6.id)